using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace DevExpress_gridcontrol_v1
{
    public partial class Form1 : Form
    {
        string connectionString = @"Data Source=DESKTOP-HFASO34\MSSQLSERVER_EXP;Initial Catalog=""Football Players"";Integrated Security=True;";
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //footballers_dataTableAdapter1.Fill(football_PlayersDataSet1.Footballers_data);
        }
        public void list_table()
        {
            SqlDataAdapter da = new SqlDataAdapter("Select * from [Footballers_data]", connectionString);
            DataTable dt = new DataTable();
            da.Fill(dt);
            gridControl1.DataSource = dt;

        }
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            list_table();
        }
    }
}
